name: Build VIB APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Build Admin and Customer APKs
        run: gradle assembleAdminDebug assembleCustomerDebug

      - name: Upload Admin APK
        uses: actions/upload-artifact@v4
        with:
          name: VIB-ADMIN-APK
          path: app/build/outputs/apk/admin/debug/app-admin-debug.apk

      - name: Upload Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: VIB-CUSTOMER-APK
          path: app/build/outputs/apk/customer/debug/app-customer-debug.apk
